version: 2.1

restore_freshly_gem_cache: &restore_freshly_gem_cache
  restore_cache:
    keys:
      - freshly-gems-v1.338-{{ checksum "Gemfile.lock" }}
      - freshly-gems-v1.338-

bundle_install: &bundle_install
  run:
    name: Bundle Install
    command: |
      bundle check || bundle install --deployment --frozen

save_freshly_gem_cache: &save_freshly_gem_cac